import React from 'react';
import Head from 'next/head';
import Link from 'next/link';
import styles from '../styles/Home.module.css';

export default function Home() {
  return (
    <>
      <Head>
        <title>My Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.container}>
        <div className={styles.intro}>
          <h1 className={styles.title}>
            Hey, I&apos;m
            <span> Natan Manor</span>
          </h1>
          <h2 className={styles.secondaryTitle}>And I&apos;m a Full Stack Engineer</h2>
        </div>
        <section className={styles.introduction}>
          Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor
          incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud
          exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute
          irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat
          nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa
          qui officia deserunt mollit anim id est laborum.
        </section>
        <Link className={styles.portfolioButton} href="/projects">
          See my portfolio
          <span className="material-symbols-rounded">
            navigate_next
          </span>
        </Link>
      </main>
    </>
  );
}
